# Generated by Django 3.2.3 on 2021-05-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15)),
                ('rate', models.CharField(blank=True, max_length=5)),
                ('text', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
