# Generated by Django 3.2.3 on 2021-06-21 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='isTransactionComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SetupTransactionSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionSuccess', models.BooleanField(default=False)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now_add=True)),
                ('setup', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_success', to='api.setup')),
            ],
        ),
    ]
