# Generated by Django 3.2.3 on 2021-06-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='staff',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
