# Generated by Django 3.2.3 on 2021-06-25 14:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210624_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='isActive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='setup',
            name='isDeleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.BooleanField(default=False)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('wallet_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transaction', to='api.wallet')),
            ],
        ),
    ]
