# Generated by Django 3.2.3 on 2021-05-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('zip', models.CharField(blank=True, max_length=7)),
                ('photo', models.CharField(blank=True, max_length=500)),
                ('isOccupied', models.BooleanField(default=False)),
                ('isCleaned', models.BooleanField(blank=True, default=True)),
                ('createdBy', models.CharField(blank=True, max_length=4)),
                ('updatedBy', models.CharField(blank=True, max_length=4)),
            ],
        ),
    ]
