# Generated by Django 3.2.3 on 2021-05-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
