# Generated by Django 3.2.3 on 2021-06-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210625_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
