# Generated by Django 3.2.3 on 2021-05-28 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_setup_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='occupiedBy',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('isRead', models.BooleanField(default=False)),
                ('createdAt', models.DateField()),
                ('updatedAt', models.DateField()),
                ('setup', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='setups', to='api.setup')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='userss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
