# Generated by Django 3.2.3 on 2021-05-28 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_setup_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='isOccupied',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='setup',
            name='occupiedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
