# Generated by Django 3.2.3 on 2021-05-28 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210528_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='createdAt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updatedAt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=30)),
                ('money', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('setup', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='setup', to='api.setup')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
