# Generated by Django 3.2.3 on 2021-05-29 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210528_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='createdAt',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updatedAt',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
