# Generated by Django 3.2.3 on 2021-07-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
