# Generated by Django 3.2.3 on 2021-05-29 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210529_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='createdAt',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='contactus',
            name='updatedAt',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='feedback',
            name='createdAt',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='feedback',
            name='updatedAt',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='setup',
            name='createdAt',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='setup',
            name='updatedAt',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='transaction',
            name='createdAt',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updatedAt',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
