# Generated by Django 3.2.3 on 2021-07-01 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('isRead', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('setup', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notification_setups', to='api.setup')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notification_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
