# Generated by Django 3.2.3 on 2021-07-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_adminnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='setup',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
