# Generated by Django 3.2.3 on 2021-05-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_setup_occupytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mobile',
            field=models.IntegerField(default=7385788325),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
