# Generated by Django 3.2.3 on 2021-07-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210701_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='latitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='setup',
            name='longitude',
            field=models.CharField(max_length=50),
        ),
    ]
