# Generated by Django 3.2.3 on 2021-07-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210705_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
