# Generated by Django 3.2.14 on 2022-07-18 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210705_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='wallet_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet_transaction', serialize=False, to='api.wallet'),
        ),
    ]
