# Generated by Django 3.2.14 on 2022-07-18 10:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220718_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='wallet_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transaction', to='api.wallet'),
        ),
    ]
